FROM centos:7
WORKDIR /opt/
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.86/bin/apache-tomcat-9.0.86.tar.gz .
COPY jdk-11.0.17_linux-x64_bin.rpm .
RUN rpm -ivh jdk-11.0.17_linux-x64_bin.rpm && \
   tar -xzf apache-tomcat-9.0.86.tar.gz && \
   chmod -R 777 apache-tomcat-9.0.86 && \
   ln -sf "/usr/share/zoneinfo/Asia/Kolkata" /etc/localtime && \
   rm -rf jdk-11.0.17_linux-x64_bin.rpm apache-tomcat-9.0.86.zip
WORKDIR /opt/apache-tomcat-9.0.86/webapps
COPY session.war .
EXPOSE 8080
WORKDIR /opt/apache-tomcat-9.0.86/bin
RUN chmod -R 777 *
########################   Added V2 ###################
WORKDIR /opt/apache-tomcat-9.0.86/webapps/host-manager/META-INF
RUN rm -rf context.xml
COPY context.xml .
WORKDIR /opt/apache-tomcat-9.0.86/webapps/manager/META-INF
RUN rm -rf context.xml
COPY context.xml .
WORKDIR /opt/apache-tomcat-9.0.86/conf
RUN rm -rf tomcat-users.xml
COPY tomcat-users.xml .
CMD ["/opt/apache-tomcat-9.0.86/bin/catalina.sh", "run"]
